version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  checkout:
    executor:
      name: node/default
    steps:
      - checkout
  install:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm install
  lint:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm lint
  test:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm test
  build-node:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm test      
  build-web:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm test   
workflows:
    build-and-test:
      jobs:
        - checkout
        - install:
            requires:
              - checkout
        - lint:
            requires:
              - install
        - test:
            requires:
              - install
        - build-node:
            requires:
              - test
        - build-web:
            requires:
              - test
